-- Profiles Table
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  weight DECIMAL(5, 2), -- kg
  height DECIMAL(5, 2), -- cm
  age INT,
  gender TEXT CHECK (gender IN ('male', 'female', 'other')),
  activity_level TEXT CHECK (activity_level IN ('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extra_active')),
  goal TEXT CHECK (goal IN ('weight_loss', 'maintenance', 'cut', 'bulk')) DEFAULT 'maintenance',
  tdee INT, -- Estimated Daily Total Energy Expenditure
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Calorie Logs Table
CREATE TABLE calorie_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  food_name TEXT NOT NULL,
  calories DECIMAL(7, 2) NOT NULL,
  protein DECIMAL(5, 2),
  fat DECIMAL(5, 2),
  carbs DECIMAL(5, 2),
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE calorie_logs ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles (Using id instead of user_id)
CREATE POLICY "Users can view their own profiles" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profiles" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profiles" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Policies for Calorie Logs
CREATE POLICY "Users can view their own calorie logs" ON calorie_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own calorie logs" ON calorie_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own calorie logs" ON calorie_logs FOR DELETE USING (auth.uid() = user_id);
